### ISSUE TITLE
Add button to display additional snippets even if their hasn't been mentioned in job description.

### ISSUE THREAD

**Issue by mattcheah** [mattcheah/cover-letter-snippets#2]
After parsing a job description, in `ResultsComponent`, the only categories that are displayed are the ones that have matches in the job description. However, this isn't always practical. For example, if a job is looking for javascript developers who have experience in javascript frameworks, a category for Angular or React isn't going to show up. Users need to have the ability to scroll through additional categories even if there are no matches in the job description text. 

This change can be made in `ResultsComponent`. The results are currently being displayed and filtered by a pipe `hasKeywords`. You could change the pipe so you can pass values to it (eg. `showAllValues: showAllValues` and on the Show More Button: `(click)="showAllValues = !showAllValues"`) 
Or you can do it however else you want. 

This is a fairly quick fix for newcomers, and I would love to help in any way possible so just let me know if anyone wants to take this on and needs help. Thanks!

**Comment by mattcheah** [comment]
Hey, sounds great, thanks for offering to help out! I’d love to offer any
help you need understanding the program, and I’d also love to hear any
recommendations and constructive criticism about the code. Let me know,
thanks!

**Comment by treventrujillo** [comment]
<img width="686" alt="cover-letter-snippets-error" src="https://user-images.githubusercontent.com/29497402/45128882-a722d780-b13d-11e8-8961-264cccf5ade5.png">

I've been stuck on this error for a minute. I followed the README's instructions to set up the application with the database, but it seems I'm missing an important step in the build. It looks like it's breaking in routes.js line 4. Any idea what I could do?

**Comment by mattcheah** [comment]
Hey, sorry you’re having trouble.
I’m not near a computer right now so I can’t walk you through it, but try
going to the folder where node modules are installed globally (sorry not
sure where that is on a Mac) and check if there’s a db-routes.js file. If
there isn’t, try to reinstall the package (but it’s probable that I did
something wrong with the npm package)

For a workaround you can fork the repo and run ‘node index’ in the main
directory. That should make sure that all the required files are there.

**Comment by treventrujillo** [comment]
Forking the repo and running node index worked, thanks.

**Comment by mattcheah** [comment]
I think I fixed your previous issue -  I had spelled something wrong in the package.json so those routes weren't being picked up. Let me know how you're doing!

**Comment by treventrujillo** [comment]
Good to hear! So far I've used the hasKeywords pipe to display the other keywords in the keywordArray that had 0 jobKeyword matches. When I get the time tonight, I'll be finishing wiring it up to the UI. This will be my first pull request so I ask that you give me honest feedback on my work, as it will really help me improve. Thanks!
