### ISSUE TITLE
Sort addable snippets by which ones have the most relevant categories in the job description.

### ISSUE THREAD

**Issue by mattcheah** [mattcheah/cover-letter-snippets#6]
Addable snippets with the most amount of categories that match job description keywords should be the first ones to show up in the list. eg. If a job description asks for Java, C, Python, and R, my saved cover letter snippet that mentions Java, C, and Python should show up above my snippet that just mentioned Java, or even one that mentions Java and R. 

Let me know if you'd like to help out and I'll provide any information I can!

**Comment by slay4joy** [comment]
Hello Matt! I'm a junior developer looking to improve my Angular skills. I'd love to help your project.

**Comment by mattcheah** [comment]
@slay4joy awesome! Let me know if you need any help getting started. I can think of a couple ways to accomplish this but you should try it out on your own first. 
Thanks for helping out!

**Comment by slay4joy** [comment]
@mattcheah so, how do I do this? Do I just pick any issue, like this one, and then make a pull request once I finish the work?

**Comment by mattcheah** [comment]
Yep! I assumed you wanted to work on this one but if you want to work on another just comment in there, fork the repo, and make a pull request.

**Comment by slay4joy** [comment]
Hey man, created a pull request, you can check it out.
