### ISSUE TITLE
The Readme isn't clear.

### ISSUE THREAD

**Issue by vedabrat** [mattcheah/cover-letter-snippets#7]
Specifically for solving issues, I'm not able to get the gist of what this site is or how to get it up and running locally so that I can either make changes or contribute to it. Updating the readme as per a getting started up and running methodology would help greatly.

**Comment by mattcheah** [comment]
Thanks @vedabrat, with regards to getting it up and running, did you run into any installation issues or problems with running snippets? You can check the section labeled “Using Snippets” in the readme. Thanks!

**Comment by vedabrat** [comment]
@mattcheah, I'm assuming that if your code wished to be edited, the interface for getting the application to run locally on a webpage has to be had. If this was a rails app, something simple like
'git clone "therepo"
cd cover-letter-snippets
bundle install
rails s'
would be sufficient. 

Im currently assuming this is an npm package, but havent gotten it to run locally yet.

**Comment by mattcheah** [comment]
Hi @vedabrat, 
Yes, it is an npm package. What step did you get to before you ran into issues? 
The first step is to install with `npm i -g cover-letter-snippets`
The second step is to run with `snippets`

I've updated the Readme a little bit to put the installation and running instructions at the top instead of underneath the "setting up a database" section. Let me know if that makes more sense. Thanks!

**Comment by vedabrat** [comment]
Okay, I've gotten further (up to the point where intros and outros are being addressed), but I have not loaded any (and couldn't figure out how to).  I haven't been able to progress to export a cover letter yet.

**Comment by mattcheah** [comment]
That's great! 
Can you be more specific? You have not loaded any Intros or Outros?
The readme says you can add an "intro" and "outro" category. Did you try doing that? 

You'll be able to progress to export a cover letter after you add some snippets to your cover letter. Have you selected a snippet category after parsing a job description? Have you added any snippets from that category? 

The more details you can give me, the more I know how to fix the readme. You can even make a PR to make the readme a little more clear if you need to. Thanks!

**Comment by mattcheah** [comment]
closing this as I haven't received a response and I have updated the readme.
